---
language: python
services: docker
install:
- pip install pipenv
- pipenv install
script:
- pipenv run molecule test
notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
